devtools::install_github('gilead-biostats/clindata')
devtools::install_github('gilead-biostats/gsm@gsm-core-test')
devtools::install_github('gilead-biostats/gsm.mapping@dev')
devtools::install_github('gilead-biostats/gsm.kri@dev')
devtools::install_github('gilead-biostats/gsm.reporting@dev')
# or gsm git checkout branch and devtools::load_all()

library(dplyr)
library(clindata)
library(gsm)
library(gsm.mapping)
library(gsm.kri)
library(gsm.reporting)
library(yaml)
